var round="http://liveticker.ergotipp.de/fb_mbl/feed/s2014/md3/dpa/30_onl1.xml",all="http://liveticker.ergotipp.de/fb_mbl/feed/s2014/md3a/onl1.xml?v=1234",proxy="proxy.php",teams={t156:"Bayern",t172:"Wolfsburg",t159:"Frankfurt",t160:"Freiburg",t162:"Berlin",t171:"Bremen",t387:"K\u00f6ln",t161:"Hamburg",t808:"Hannover",t167:"Schalke",t1902:"Hoffenheim",t1772:"Augsburg",t157:"Dortmund",t164:"Leverkusen",t1743:"Paderborn",t810:"Mainz",t683:"Gladbach",t169:"Stuttgart"},tips={},userPunkte={},winAmount=
userNames.length;function getRandom(){return 899999*Math.random()+1E5}
$(function(){$(".scrollTop").on("click",function(){window.scrollTo(0,0)});$("table").on("focus",'input[type="tel"]',function(a){"x"==$(this).val()&&$(this).val("")});$("table").on("keyup",'input[type="tel"]:nth-child(2)',function(a){a=$(this).val();$.isNumeric(a)?(saveTip($(this).parent().data("spiel"),$(this).parent().data("eventid"),$(this).parent().parent().data("user"),$(this).closest("table").attr("id").split("round")[1],a,1),$(this).next('input[type="tel"]').focus(),$(this).next('input[type="tel"]').val($(this).next('input[type="tel"]').val())):
$(this).val("")});$("table").on("keyup",'input[type="tel"]:nth-child(3)',function(a){a=$(this).val();$.isNumeric(a)?(saveTip($(this).parent().data("spiel"),$(this).parent().data("eventid"),$(this).parent().parent().data("user"),$(this).closest("table").attr("id").split("round")[1],a,2),$(this).closest("td").next().next().find('input[type="tel"]:first').focus(),$(this).closest("td").next().next().find('input[type="tel"]:first').val($(this).closest("td").next().next().find('input[type="tel"]:first').val())):
$(this).val("")});$("table:gt("+(actRound-1)+")").on("click",".rotKnopf",function(a){$(this).parent().parent().find("td").each(function(){$(this).data("rot",!1).removeClass("rot")});$(this).parent().data("rot",!0).addClass("rot");saveRot($(this).parent().data("spiel"),$(this).parent().parent().data("user"),$(this).parent().closest("table").attr("id").split("round")[1])});$('td input[type="checkbox"]:enabled').on("change",function(){var a=$(this).closest("table").attr("id").split("round")[1],b=$(this).parent().parent().data("user"),
c=$(this).prop("checked")?1:0;$.ajax({method:"GET",url:"ajax.php",cache:!1,data:{action:"saveBez",round:a,user:b,bezahlt:c,rnd:getRandom()},dataType:"json"})});$(".tableHeader").on("click",function(){$(this).parent().find("tr:not(.tableHeader):not(.erg)").toggle()});getTable("tableList");getInjured("tableInjured");$(".begegnung img").on("mouseover",function(){var a=$(this).data("teamid");$("img."+a).addClass("highTeam")});$(".begegnung img").on("mouseout",function(){var a=$(this).data("teamid");$("img."+
a).removeClass("highTeam")})});function saveTip(a,b,c,d,f,e){$.ajax({method:"GET",url:"ajax.php",cache:!1,data:{action:"saveTip",spiel:a,user:c,round:d,tipp:f,typ:e,eventId:b,rnd:getRandom()},dataType:"json"}).done(function(a){})}function saveRot(a,b,c){$.ajax({method:"GET",url:"ajax.php",cache:!1,data:{action:"saveRot",spiel:a,user:b,round:c,rnd:getRandom()},dataType:"json"}).done(function(a){})}
function sumPoints(){for(var a in userPunkte)userPunkte[a].totalPoints=0,userPunkte[a].wins=0;$(".punkte").each(function(){var a=0;$(this).closest("table").data("spieltag");var b=$(this).parent().data("user");$(this).parent().find(".matchpoints").each(function(){a+=parseInt($(this).html())});$(this).html(a);"undefined"==typeof userPunkte[b]&&(userPunkte[b]={});"undefined"==typeof userPunkte[b].totalPoints&&(userPunkte[b].totalPoints=0);userPunkte[b].totalPoints+=a});for(d=1;d<actSpieltag;d++)markWinner(d);
a=[];for(var b in userPunkte)a.push([b,userPunkte[b]]);a.sort(function(a,b){return b[1].totalPoints-a[1].totalPoints});b="";var c=1,d;for(d in a)"undefined"==typeof a[d][1].wins&&(a[d][1].wins=0),b+='<tr class="pointsTR"><td class="pointsName">'+userNames[a[d][0]-1]+"</td><td>"+a[d][1].totalPoints+"</td><td>"+c+"</td><td>"+a[d][1].wins+" &euro;</td></tr>",c++;$(".pointsTR").remove();$("#points").append(b)}
function Spieltag(a,b){this.round=a;this.matches="";this.tips=tips[this.round];"undefined"==typeof b?this.loadMatches(!0):this.loadMatches(!1)}
Spieltag.prototype={loadMatches:function(a){var b=this;$.ajax({type:"GET",url:proxy+"?type=round&round="+this.round,cache:!1,dataType:"xml"}).done(function(c){$.parseXML(c);b.Matches=c;a&&b.writeResults();b.calculatePoints()})},writeMatches:function(){var a="";$(this.Matches).find("fixture").each(function(){var b=$(this).find("teamHome").attr("teamId"),c=$(this).find("teamAway").attr("teamId");a+='<th><img src="img/'+b+'.png" title="'+teams[b]+'"/> <img src="img/'+c+'.png" title="'+teams[c]+'"/></th><th></th>'});
$(a).insertAfter("#round"+this.round+" .spieltag")},writeResults:function(){$("#round"+this.round+" .erg").remove();var a=this,b='<tr class="erg"><td>Erg</td>';$("#round"+this.round+" th.begegnung").each(function(){var c=$(this).data("eventid"),d=$(spieltag.Matches).find("fixture[eventId="+c+"]"),f=$(d).find("teamHome score").attr("total"),f="undefined"==typeof f?"x":f,e=$(d).find("teamAway score").attr("total"),e="undefined"==typeof e?"x":e;$(d).find("teamHome").attr("teamId");b+="<td>"+f+" - "+
e+"</td><td></td>";a.saveResults(f,e,c)});b+="<td></td><td></td></tr>";$("#round"+this.round).append(b)},loadTips:function(){var a="",b;for(b in this.tips){var a=a+('<tr data-user="'+b+'"><td class="name">'+this.tips[b].name+"</td>"),c;for(c in this.tips[b].tips)var d=this.tips[b].rot==c?d=' data-rot="true" class="rot"':"",a=a+('<td data-spiel="'+c+'" '+d+' class="tiptd"><input type="tel" value="'+this.tips[b].tips[c].home+'"  /> - <input type="tel" value="'+this.tips[b].tips[c].away+'" /></td><td class="matchpoints" data-spiel="'+
c+'"></td>');a+='<td><input type="checkbox" /></td><td class="punkte"></td></tr>'}$(a).insertAfter("#round"+this.round+" .tableHeader");this.calculatePoints()},calculatePoints:function(){var a=this,b;for(b in tips[a.round])tips[this.round][b].punkte=0;$("#round"+this.round+" .matchpoints").each(function(){$(this).data("spiel");var b=$(this).parent().data("user"),d=$(this).prev().data("eventid"),f=$(this).prev().hasClass("rot")?!0:!1;if(a.round<actRound)var e=$(this).prev().text().split(" - ")[0],
g=$(this).prev().text().split(" - ")[1];else e=$($(this).prev().find("input")[0]).val(),g=$($(this).prev().find("input")[1]).val();if($.isNumeric(e)&&$.isNumeric(g)){var d=$(a.Matches).find("fixture[eventId="+d+"]").attr("eventId"),h=$(a.Matches).find("fixture[eventId="+d+"] teamHome score").attr("total"),k=$(a.Matches).find("fixture[eventId="+d+"] teamAway score").attr("total");punkte=0;tipp_sieger=e==g?"unent":e>g?"heim":"gast";real_sieger=h==k?"unent":h>k?"heim":"gast";real_sieger==tipp_sieger&&
(punkte=1,h==e&&k==g&&(punkte=2),f&&(punkte*=2));"undefined"==typeof h&&(punkte=0);a.savePoints(d,b,punkte);$(this).html(punkte)}});sumPoints()},refresh:function(a){this.loadMatches(!1)},saveResults:function(a,b,c){"x"!=a&&$.ajax({type:"GET",url:"ajax.php",cache:!1,data:{action:"saveResult",erg1:a,erg2:b,eventId:c,rnd:getRandom()},dataType:"json"})},savePoints:function(a,b,c){$.ajax({type:"GET",url:"ajax.php",cache:!1,data:{action:"savePoints",eventId:a,user:b,punkte:c,rnd:getRandom()},dataType:"json"})}};
var actRound=actSpieltag,spieltag=new Spieltag(actRound),timeoutID=window.setInterval(function(){spieltag.refresh(!0)},5E3);
function getTable(a){var b=1E3;$.ajax({type:"GET",url:proxy+"?type=table&matchday="+(actRound-1),cache:!1,dataType:"xml"}).done(function(c){$xml=$(c);$title=$xml.find("sports-title");var d="";$xml.find("standing team").each(function(){$(this).find("name").attr("full");var a=$(this).find("team-metadata").attr("team-key"),c=$($(this).find("outcome-totals")[0]).attr("standing-points");d+='<div class="vTeam" style="z-index:'+b+'"><div class="vLogo"><img src="svg/'+a+'_original.svg" /></div>';d+='<div class="vPunkte">'+
c+"</div>";d+="</div>";b--});$("#"+a).prepend(d)})}
function getInjured(a){$.ajax({type:"GET",url:proxy+"?type=injured",cache:!1,dataType:"json"}).done(function(b){var c="",d;for(d in b)c+="<tr>",c+="<td><img src='img/"+b[d].typ+".png' title='"+b[d].typ+"' alt='"+b[d].typ+"'/></td>",c+="<td>"+b[d].name+"</td>",c+="<td><span title='"+b[d].news+"'>",c+=23<b[d].news.length?b[d].news.substring(0,23)+"...":b[d].news,c+="</span></td>",c+="<td class='tage'>"+b[d].fehlt+"</td>",c+="</tr>";$("#"+a).append(c)})}
function markWinner(a){var b=-1,c=0;$("#div"+a+" .punkte").each(function(){var a=parseInt($(this).text());b<a&&(b=a)});$("#div"+a+" .punkte").each(function(){parseInt($(this).text())==b&&0<b&&($(this).parent().addClass("dayWinner"),c++)});$("#div"+a+" .dayWinner").each(function(){var a=$(this).data("user");"undefined"==typeof userPunkte[a].wins&&(userPunkte[a].wins=0);userPunkte[a].wins+=Math.floor(winAmount/c)})};